Modernize repo
AlaskaAirlines/auro-drawer pull request #5
Opened 2024-01-24 19:24 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #1, #2

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Rebuild component using generator
* Add theming support
* Add SSR support
* Refactor documentation, tests and style src code

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-01-24 20:28 UTC, jason-capsule42 approved these changes

2024-01-25 02:02 UTC, blackfalcon requested changes

2024-01-25 02:02 UTC, blackfalcon commented on docs/partials/index.md
> +</auro-accordion>
Delete this content

2024-01-25 02:02 UTC, blackfalcon commented on docs/partials/index.md
> +Having a closing statement about your example helps to really complete the thought with your reader.
None of this makes sense? Where are all the examples currently shown here? https://auro.alaskaair.com/components/auro/interruption/drawer

2024-01-25 02:02 UTC, blackfalcon commented on docs/partials/index.md
> +Having a closing statement about your example helps to really complete the thought with your reader.
I see that the examples that were on the demo page are now in the API page, but none of those examples line up with the API references? All the API attributes have links that should be linked to content in the page. 

I would expect something like recently done with auro-lockup.

2024-01-25 08:40 UTC, leeejune reviewed
It seems like there is no padding/margin on the sides.

# Original drawer
<img width="1560" alt="Screenshot 2024-01-25 at 12 39 27 AM" src="https://github.com/AlaskaAirlines/auro-drawer/assets/55998746/f22a46f6-ccca-4e75-90f7-9b0acc821fe6">

# PR drawer
<img width="1548" alt="Screenshot 2024-01-25 at 12 39 37 AM" src="https://github.com/AlaskaAirlines/auro-drawer/assets/55998746/7fe63a9a-3d3c-45e4-aca9-373751e84480">

Notice the discrepancy on the sides in the two screenshots.

2024-01-25 19:17 UTC, jordanjones243 commented on docs/partials/index.md
> +</auro-accordion>
Per our discussion, we will leave this example in.

2024-01-25 19:18 UTC, jordanjones243 commented on docs/partials/index.md
> +Having a closing statement about your example helps to really complete the thought with your reader.
There have been links for the attribute examples implemented.

2024-01-25 22:29 UTC, leeejune approved these changes

2024-01-25 22:37 UTC, merged

2024-01-25 22:39 UTC, jordanjones243 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-drawer/v/1.0.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-drawer/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: